//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VM.DisasterRecovery.Persistence.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Persistence : global::System.Configuration.ApplicationSettingsBase {
        
        private static Persistence defaultInstance = ((Persistence)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Persistence())));
        
        public static Persistence Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DisasterRecoveryConnection")]
        public string ConnectionStringName {
            get {
                return ((string)(this["ConnectionStringName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Requested changes have been saved.")]
        public string UnitOfWorkCommitChangesSuccess {
            get {
                return ((string)(this["UnitOfWorkCommitChangesSuccess"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Unable able to save changes! Please try again later.")]
        public string UnitOfWorkCommitChangesFailed {
            get {
                return ((string)(this["UnitOfWorkCommitChangesFailed"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Unable able to save changes due to one or more records being in an invalid state." +
            "")]
        public string UnitOfWorkCommitChangesValidationError {
            get {
                return ((string)(this["UnitOfWorkCommitChangesValidationError"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Unable able to save changes due to one or more of the records have already have m" +
            "odified.")]
        public string UnitOfWorkCommitChangesConcurrencyError {
            get {
                return ((string)(this["UnitOfWorkCommitChangesConcurrencyError"]));
            }
        }
    }
}
